from .gemini_image_gen import (
    NODE_CLASS_MAPPINGS as GEN_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GEN_DISPLAY,
)
from .volumetric_timelapse_nodes import (
    NODE_CLASS_MAPPINGS as NB4D_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NB4D_DISPLAY,
)
from .parallax_renderer import (
    NODE_CLASS_MAPPINGS as PARALLAX_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PARALLAX_DISPLAY,
)
from .grid4d_nodes import (
    NODE_CLASS_MAPPINGS as GRID4D_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GRID4D_DISPLAY,
)
from .ltxv_interpolator import (
    NODE_CLASS_MAPPINGS as LTXV_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTXV_DISPLAY,
)
from .ltxv_interpolator_v2 import (
    NODE_CLASS_MAPPINGS as LTXV_V2_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTXV_V2_DISPLAY,
)

NODE_CLASS_MAPPINGS = {
    **GEN_MAPPINGS,
    **NB4D_MAPPINGS,
    **PARALLAX_MAPPINGS,
    **GRID4D_MAPPINGS,
    **LTXV_MAPPINGS,
    **LTXV_V2_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **GEN_DISPLAY,
    **NB4D_DISPLAY,
    **PARALLAX_DISPLAY,
    **GRID4D_DISPLAY,
    **LTXV_DISPLAY,
    **LTXV_V2_DISPLAY,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
