from .gemini_image_gen import (
    NODE_CLASS_MAPPINGS as GEN_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GEN_DISPLAY,
)

NODE_CLASS_MAPPINGS = {**GEN_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**GEN_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
